import { Component } from '@angular/core';
import * as _ from 'lodash';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  items = [
    {
      "job_template_items_id": 1,
      "job_template_id": 1,
      "job_group_id": 1,
      "job_subitem_id": 1,
      "job_process_id": 1,
      "job_group_name": "งานสารบบคดีและการบริหารงานสารบบคดี",
      "job_item_name": "งานรับสำนวนคดีแรงงาน",
      "job_process_name": "บันทึกการรับสำนวนคดีจากหน่วยงานตัวความในสารบบคดีอิเล็กทรอนิกส์",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 2,
      "job_template_id": 1,
      "job_group_id": 1,
      "job_subitem_id": 1,
      "job_process_id": 2,
      "job_group_name": "งานสารบบคดีและการบริหารงานสารบบคดี",
      "job_item_name": "งานรับสำนวนคดีแรงงาน",
      "job_process_name": "เข้าปกสำนวนคดี เข้าปกหลังพร้อมหูสำนวน พร้อมแนนใบความเห็นและคำสั่ง (อ.ก.๔)",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 3,
      "job_template_id": 1,
      "job_group_id": 1,
      "job_subitem_id": 1,
      "job_process_id": 3,
      "job_group_name": "งานสารบบคดีและการบริหารงานสารบบคดี",
      "job_item_name": "งานรับสำนวนคดีแรงงาน",
      "job_process_name": "ลงรับในสารบบความแรงงาน (ส.๕ ก) และบัญชีจ่ายสำนวน (บ.๗)",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 4,
      "job_template_id": 1,
      "job_group_id": 1,
      "job_subitem_id": 1,
      "job_process_id": 4,
      "job_group_name": "งานสารบบคดีและการบริหารงานสารบบคดี",
      "job_item_name": "งานรับสำนวนคดีแรงงาน",
      "job_process_name": "เสนออธิบดีอัยการ/รองอธิบดีอัยการ เพื่อสั่งจ่ายสำนวนไปยังสำนักงานอัยการพิเศษฝ่าย",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 5,
      "job_template_id": 1,
      "job_group_id": 1,
      "job_subitem_id": 1,
      "job_process_id": 5,
      "job_group_name": "งานสารบบคดีและการบริหารงานสารบบคดี",
      "job_item_name": "งานรับสำนวนคดีแรงงาน",
      "job_process_name": "ส่งสำนวนให้สำนักงานอัยการพิเศษฝ่ายที่ได้รับมอบหมายดำเนินการต่อไป",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 6,
      "job_template_id": 1,
      "job_group_id": 1,
      "job_subitem_id": 1,
      "job_process_id": 6,
      "job_group_name": "งานสารบบคดีและการบริหารงานสารบบคดี",
      "job_item_name": "งานรับสำนวนคดีแรงงาน",
      "job_process_name": "โอนสำนวนไปสำนักงานอัยการพิเศษฝ่ายในสารบบคดีอิเล็กทรอนิกส์ ",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 7,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 7,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "รับรายงานบัญชีสำนวนค้างคดีแรงงานและบัญชีชี้แจงเหตุที่สำนวนค้าง, บัญชีแสดงการที่ทำของพนักงานอัยการ, รายงานอัยการ (บ. ๖) จากสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 8,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 8,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "ตรวจสอบความถูกต้องของรายงานที่เสนอ",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 9,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 9,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "พิจารณาความถูกต้องของรายงาน หากถูกต้องครบถ้วนรับไว้เพื่อดำเนินการต่อไป",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 10,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 10,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "นำรายงานบัญชีค้างคดีแรงงานที่ถูกต้องครบถ้วนดำเนินการ เสนออธิบดีอัยการต่อไป",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 11,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 11,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "ส่งเรื่องคืน หากรายงานที่ได้รับผิดพลาด บกพร่องในสาระคำคัญ ",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 12,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 12,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "ตรวจสอบว่ามีรายงานชี้แจงสำนวนค้างเกิน ๓ เดือนประกอบ (กรณีมีสำนวนค้างเกิน ๓ เดือน)",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 13,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 13,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "เสนออธิบดีอัยการ (ผ่านรองอธิบดีอัยการ) พิจารณาลงนาม",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 14,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 14,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "รวบรวมรายงานที่ถูกต้องของสำนักงานอัยการพิเศษฝ่ายและสำนักอำนวยการ  ",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 15,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 15,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "ร่างหนังสือนำส่งรายงาน เสนออธิบดีอัยการ (ผ่านรองอธิบดีอัยการ)",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 16,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 16,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "พิมพ์หนังสือนำส่งตามร่างที่ผ่านการตรวจร่าง และเสนออธิบดีอัยการลงนาม",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 17,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 2,
      "job_process_id": 17,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรวบรวมรายงานสำนักงานอัยการพิเศษฝ่ายในสังกัด",
      "job_process_name": "นำส่งหนังสือนำส่งรายงานที่อธิบดีอัยการลงนาม ให้เจ้าหน้าที่ที่เกี่ยวข้องดำเนินการออกเลขหนังสือส่งและนำส่งไปรษณีย์ต่อไป",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 18,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 3,
      "job_process_id": 18,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงานผลการปฏิบัติงานคดีประจำงวด (รายไตรมาส)",
      "job_process_name": "จัดเก็บข้อมูลและรวบรวมข้อมูลการปฏิบัติงานในสารบบคดี ส.๕ ก ของไตรมาสที่ต้องรายงาน โดยตรวจสอบรายละเอียด จำนวนคดี และทุนทรัพย์ที่รับดำเนินการ, ที่เสร็จในชั้นอัยการ, ที่เสร็จในชั้นศาล ",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 19,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 3,
      "job_process_id": 19,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงานผลการปฏิบัติงานคดีประจำงวด (รายไตรมาส)",
      "job_process_name": "นำข้อมูลที่ได้มาเปรียบเทียบกับข้อมูลรายงานผลการปฏิบัติงานไตรมาสที่ผ่านมา และจัดพิมพ์รายละเอียดลงในแบบรายงานที่ ๑.๔.๑ การดำเนินคดีประจำไตรมาส",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 20,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 3,
      "job_process_id": 20,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงานผลการปฏิบัติงานคดีประจำงวด (รายไตรมาส)",
      "job_process_name": "พิมพ์บันทึกรายงานผลการปฏิบัติงานประจำไตรมาส ",
      "base_unit_id": 2,
      "base_unit_name": "วัน"
    },
    {
      "job_template_items_id": 21,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 3,
      "job_process_id": 21,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงานผลการปฏิบัติงานคดีประจำงวด (รายไตรมาส)",
      "job_process_name": "เสนออธิบดีอัยการพิจารณาลงนาม",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 22,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 3,
      "job_process_id": 22,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงานผลการปฏิบัติงานคดีประจำงวด (รายไตรมาส)",
      "job_process_name": "ส่งหนังสือที่ลงนามแล้วให้เจ้าหน้าที่ออกเลขและนำส่งหน่วยงานที่รับผิดชอบ และเก็บสำเนารายงานเข้าแฟ้ม",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 23,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 3,
      "job_process_id": 23,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงานผลการปฏิบัติงานคดีประจำงวด (รายไตรมาส)",
      "job_process_name": "ส่งรายงานผ่านเว็บไซต์ www.psb.ago.go.th",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 24,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 3,
      "job_process_id": 24,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงานผลการปฏิบัติงานคดีประจำงวด (รายไตรมาส)",
      "job_process_name": "แจ้งสำนักอำนวยการทราบ",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 25,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 25,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงานบัญชีแสดงการที่ทำของพนักงานอัยการ",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 26,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 26,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงานอัยการ บ.6",
      "base_unit_id": 1,
      "base_unit_name": "นาที"
    },
    {
      "job_template_items_id": 27,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 27,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงานสถิติคดี",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 28,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 28,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงาน อ.ก.40 พ. และ อ.ก.50 พ.",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 29,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 29,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงานบัญชีแสดงการตรวจสอบสำนวนคดีที่มีคำสั่งเด็ดขาดไม่ฟ้อง อ.ก.๕๔ ก.",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 30,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 30,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงานตามแผนปรับปรุงการควบคุมภายใน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 31,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 31,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "การรายงานผลการปฏิบัติงานตาม พรบ.ข้อมูลข่าวสารของทางราชการ ๒๕๔๐",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 32,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 32,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงานตามแผนปฏิบัติการป้องกันและปราบปรามการทุจริต",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 33,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 33,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงานการประเมินประสิทธิภาพการปฏิบัติราชการของสำนักงานอัยการสูงสุด ฯลฯ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 34,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 4,
      "job_process_id": 34,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานรายงาน",
      "job_process_name": "รายงานการจัดเก็บข้อมูลการปฏิบัติงานของหน่วยงานในสังกัดสำนักงานอัยการสูงสุด",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 35,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 5,
      "job_process_id": 35,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานคำสั่งแต่งตั้ง/มอบหมาย",
      "job_process_name": "จัดคำสั่งแต่งตั้งคณะทำงานคดีสำคัญ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 36,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 5,
      "job_process_id": 36,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานคำสั่งแต่งตั้ง/มอบหมาย",
      "job_process_name": "จัดทำคำสั่งมอบหมาย รองอธิบดีอัยการ ตรวจสอบสำนวนค้างและการสั่งสำนวนที่ไม่เป็นไปตามระเบียบ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 37,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 5,
      "job_process_id": 37,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานคำสั่งแต่งตั้ง/มอบหมาย",
      "job_process_name": "คำสั่งแต่งตั้งอนุกรรมการกลั่นกรองผลการประเมินของข้าราชการธุรการ และพนักงานราชการ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 38,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 5,
      "job_process_id": 38,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานคำสั่งแต่งตั้ง/มอบหมาย",
      "job_process_name": "คำสั่งแต่งตั้งเลขานุการ สำนักงาน...........",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 39,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 5,
      "job_process_id": 39,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานคำสั่งแต่งตั้ง/มอบหมาย",
      "job_process_name": "คำสั่งแต่งตั้งคณะทำงานพิจารณาสำนวนคดี",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 40,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 6,
      "job_process_id": 40,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานขออนุมัติ",
      "job_process_name": "งานขออนุมัติเดินทางไปราชการ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 41,
      "job_template_id": 1,
      "job_group_id": 2,
      "job_subitem_id": 6,
      "job_process_id": 41,
      "job_group_name": "งานสนับสนุนงานพนักงานอัยการ",
      "job_item_name": "งานขออนุมัติ",
      "job_process_name": "งานขออนุมัติปฏิบัติงานนอกเวลาราชการ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 42,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 7,
      "job_process_id": 42,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานรับหนังสือราชการ",
      "job_process_name": "รับหนังสือราชการจากหน่วยงานภายนอก, หนังสือเวียนสำนักงานอัยการสูงสุด, หนังสือจากไปรษณีย์, หรือหนังสือไปรษณีย์อิเล็กทรอนิกส์",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 43,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 7,
      "job_process_id": 43,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานรับหนังสือราชการ",
      "job_process_name": "ลงรับหนังสือในสารบรรณอิเล็กทรอนิกส์ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 44,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 7,
      "job_process_id": 44,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานรับหนังสือราชการ",
      "job_process_name": "ลงรับในทะเบียนรับหนังสือ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 45,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 7,
      "job_process_id": 45,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานรับหนังสือราชการ",
      "job_process_name": "เสนอผู้บังคับบัญชาตามลำดับชั้นเพื่อพิจารณามีความเห็นหรือสั่งจ่าย",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 46,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 7,
      "job_process_id": 46,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานรับหนังสือราชการ",
      "job_process_name": "ส่งหนังสือให้ผู้ที่ผู้บังคับบัญชาสั่งจ่ายเพื่อดำเนินการต่อไป",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 47,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 7,
      "job_process_id": 47,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานรับหนังสือราชการ",
      "job_process_name": "ให้ผู้ที่ได้รับมอบหมายจากผู้บังคับบัญชาลงลายมือชื่อรับ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 48,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 8,
      "job_process_id": 48,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานจัดทำหนังสือราชการ",
      "job_process_name": "งานร่างหนังสือ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 49,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 8,
      "job_process_id": 49,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานจัดทำหนังสือราชการ",
      "job_process_name": "เสนอตรวจร่าง/แก้ไข",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 50,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 8,
      "job_process_id": 50,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานจัดทำหนังสือราชการ",
      "job_process_name": "พิมพ์หนังสือ ตรวจร่าง/ทาน เสนอลงนาม ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 51,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 9,
      "job_process_id": 51,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานส่งหนังสือราชการ",
      "job_process_name": "รับหนังสือที่จะส่งจากเจ้าของเรื่อง ออกเลขหนังสือส่งในสารบรรณอิเล็กทรอนิกส์",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 52,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 9,
      "job_process_id": 52,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานส่งหนังสือราชการ",
      "job_process_name": "ลงข้อมูลในสมุดคุมหนังสือส่งของสำนักงาน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 53,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 9,
      "job_process_id": 53,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานส่งหนังสือราชการ",
      "job_process_name": "นำหนังสือใส่ซอง พิมพ์ที่อยู่ ที่ส่ง ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 54,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 9,
      "job_process_id": 54,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานส่งหนังสือราชการ",
      "job_process_name": "ลงรายละเอียดในใบนำส่งไปรษณีย์",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 55,
      "job_template_id": 1,
      "job_group_id": 3,
      "job_subitem_id": 9,
      "job_process_id": 55,
      "job_group_name": "งานสารบรรณ",
      "job_item_name": "งานส่งหนังสือราชการ",
      "job_process_name": "นำส่ง ณ ที่ทำการไปรษณีย์ หรือนำส่งหน่วยงานที่อยู่ภายในอาคารเดียวกัน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 56,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 10,
      "job_process_id": 56,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานวันลา",
      "job_process_name": "๑. รับใบลาพักผ่อน ใบลากิจ ลาป่วย และลาราชการกรณีอื่น ๆ จากข้าราชการหรือสำนักงานอัยการพิเศษฝ่ายในสังกัด ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 57,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 10,
      "job_process_id": 57,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานวันลา",
      "job_process_name": " ๒. จัดทำ ลงทะเบียนข้อมูลสถิติวันลา",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 58,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 10,
      "job_process_id": 58,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานวันลา",
      "job_process_name": " ๓. เสนอผู้บังคับบัญชาตามลำดับชั้น เพื่ออนุญาตการลา",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 59,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 10,
      "job_process_id": 59,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานวันลา",
      "job_process_name": " ๔. ส่งกลับสำนักงานอัยการพิเศษฝ่ายเพื่อเก็บไว้เป็นหลักฐาน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 60,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 10,
      "job_process_id": 60,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานวันลา",
      "job_process_name": "๕. การรายงานวันลาหยุดของข้าราชการอัยการและข้าราชการธุรการ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 61,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 11,
      "job_process_id": 61,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการธุรการ",
      "job_process_name": "รับรายงานผลการปฏิบัติราชการของข้าราชการธุรการที่ประเมินตนเองและได้รับการประเมินจากอัยการพิเศษฝ่าย เสนออธิบดีอัยการ (ผ่านรองอธิบดีอัยการ) เพื่อพิจารณาประเมินผล",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 62,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 11,
      "job_process_id": 62,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการธุรการ",
      "job_process_name": "จัดพิมพ์บัญชีรายงานผลการประเมินการปฏิบัติราชการของข้าราชการธุรการประจำงวดที่อธิบดีอัยการประเมินผลแล้ว เสนออธิบดีอัยการลงลายมือชื่อ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 63,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 11,
      "job_process_id": 63,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการธุรการ",
      "job_process_name": "ร่างหนังสือส่งรายงานประเมินผลการปฏิบัติราชการ เสนอผู้ได้รับมอบหมายตรวจร่าง",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 64,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 11,
      "job_process_id": 64,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการธุรการ",
      "job_process_name": "พิมพ์หนังสือส่งรายงานประเมินผลการปฏิบัติราชการของข้าราชการธุรการเสนอพร้อมบัญชีรายงานผลการประเมินผล เสนออธิบดีอัยการลงลายมือชื่อ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 65,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 11,
      "job_process_id": 65,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการธุรการ",
      "job_process_name": "ออกเลขหนังสือนำส่ง และนำส่ง ณ ที่ทำการไปรษณีย์ (พิมพ์ที่อยู่ปะหน้า ใส่ซอง จัดทำใบนำส่งไปรษณีย์)",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 66,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 12,
      "job_process_id": 66,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการอัยการ",
      "job_process_name": "รับรายงานผลการปฏิบัติราชการของข้าราชการอัยการที่ประเมินตนเองหรือจากที่ได้รับการประเมินจากอัยการพิเศษฝ่าย เสนออธิบดีอัยการ (ผ่านรองอธิบดีอัยการ) เพื่อพิจารณาประเมินผล",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 67,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 12,
      "job_process_id": 67,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการอัยการ",
      "job_process_name": "จัดพิมพ์บัญชีรายงานผลการประเมินการปฏิบัติราชการของข้าราชการอัยการประจำงวดที่อธิบดีอัยการประเมินผลแล้ว เสนออธิบดีอัยการลงลายมือชื่อ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 68,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 12,
      "job_process_id": 68,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการอัยการ",
      "job_process_name": "ร่างหนังสือส่งรายงานประเมินผลการปฏิบัติราชการของข้าราชการอัยการ เสนอผู้ได้รับมอบหมายตรวจร่าง",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 69,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 12,
      "job_process_id": 69,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการอัยการ",
      "job_process_name": "พิมพ์หนังสือส่งรายงานประเมินผลการปฏิบัติราชการของข้าราชการอัยการเสนอพร้อมบัญชีรายงานผลการประเมินผล เสนออธิบดีอัยการลงลายมือชื่อ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 70,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 12,
      "job_process_id": 70,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานประเมินผลการปฏิบัติราชการของข้าราชการอัยการ",
      "job_process_name": "ออกเลขหนังสือนำส่ง และนำส่ง ณ ที่ทำการไปรษณีย์ (พิมพ์ที่อยู่ปะหน้า ใส่ซอง จัดทำใบนำส่งไปรษณีย์)",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 71,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 13,
      "job_process_id": 71,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานยื่นข้อมูลเพื่อประกอบการบริหารงานบุคคล",
      "job_process_name": "รวบรวมแบบประกอบการพิจารณาโยกย้ายของข้าราชการอัยการและข้าราชการธุรการในสังกัด เพื่อยื่นข้อมูลเพื่อประกอบการโยกย้ายประจำปี",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 72,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 13,
      "job_process_id": 72,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานยื่นข้อมูลเพื่อประกอบการบริหารงานบุคคล",
      "job_process_name": "ร่างหนังสือนำส่งแบบประกอบการพิจารณาโยกย้าย เสนอผู้มีอำนาจตรวจร่าง",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 73,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 13,
      "job_process_id": 73,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานยื่นข้อมูลเพื่อประกอบการบริหารงานบุคคล",
      "job_process_name": "พิมพ์หนังสือนำส่งแบบประกอบการพิจารณาโยกย้าย เสนอผู้บังคับบัญชาลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 74,
      "job_template_id": 1,
      "job_group_id": 4,
      "job_subitem_id": 13,
      "job_process_id": 74,
      "job_group_name": "งานบริหารงานบุคคล(ตามระเบียบฯว่าด้วยการบริหารบุคคล)",
      "job_item_name": "งานยื่นข้อมูลเพื่อประกอบการบริหารงานบุคคล",
      "job_process_name": "ออกเลขหนังสือนำส่ง และนำส่ง ณ ที่ทำการไปรษณีย์ (พิมพ์ที่อยู่ปะหน้า ใส่ซอง จัดทำใบนำส่งไปรษณีย์)",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 75,
      "job_template_id": 1,
      "job_group_id": 5,
      "job_subitem_id": 14,
      "job_process_id": 75,
      "job_group_name": "งานเลขานุการนักบริหาร",
      "job_item_name": "งานเลขานุการนักบริหาร",
      "job_process_name": "ตรวจสอบกลั่นกรองเสนอเรื่องผู้บริหาร",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 76,
      "job_template_id": 1,
      "job_group_id": 5,
      "job_subitem_id": 14,
      "job_process_id": 76,
      "job_group_name": "งานเลขานุการนักบริหาร",
      "job_item_name": "งานเลขานุการนักบริหาร",
      "job_process_name": "ประสานงานจัดทำตารางนัดหมายของผู้บริหาร",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 77,
      "job_template_id": 1,
      "job_group_id": 5,
      "job_subitem_id": 14,
      "job_process_id": 77,
      "job_group_name": "งานเลขานุการนักบริหาร",
      "job_item_name": "งานเลขานุการนักบริหาร",
      "job_process_name": "ติดต่อประสานงานจัดทำตารางนัดหมายของผู้บริหาร",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 78,
      "job_template_id": 1,
      "job_group_id": 5,
      "job_subitem_id": 14,
      "job_process_id": 78,
      "job_group_name": "งานเลขานุการนักบริหาร",
      "job_item_name": "งานเลขานุการนักบริหาร",
      "job_process_name": "อำนวยความสะดวกรวบรวมติดตามข้อมูลเพื่อเสนอผู้บริหาร",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 79,
      "job_template_id": 1,
      "job_group_id": 5,
      "job_subitem_id": 14,
      "job_process_id": 79,
      "job_group_name": "งานเลขานุการนักบริหาร",
      "job_item_name": "งานเลขานุการนักบริหาร",
      "job_process_name": "จัดเตรียมเอกสารประกอบการประชุมแก่ผู้บริหาร",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 80,
      "job_template_id": 1,
      "job_group_id": 6,
      "job_subitem_id": 15,
      "job_process_id": 80,
      "job_group_name": "งานงบประมาณ (ตามระเบียบฯว่าด้วยงบประมาณ)",
      "job_item_name": "งานงบประมาณ (ตามระเบียบฯว่าด้วยงบประมาณ)",
      "job_process_name": "จัดทำคำขอตั้งงบประมาณรายจ่ายประจำปีเพื่อของบประมาณประจำปี ประกอบกระบวนงานดังนี้ ๑. ตรวจสอบรายการใช้จ่ายเงินของปีงบประมาณที่ผ่านมา ๒. ประมาณการรายการค่าใช้จ่ายปีที่จะของบประมาณ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 81,
      "job_template_id": 1,
      "job_group_id": 6,
      "job_subitem_id": 15,
      "job_process_id": 81,
      "job_group_name": "งานงบประมาณ (ตามระเบียบฯว่าด้วยงบประมาณ)",
      "job_item_name": "งานงบประมาณ (ตามระเบียบฯว่าด้วยงบประมาณ)",
      "job_process_name": "จัดทำและพิมพ์ประมาณรายจ่ายพร้อมเอกสารประกอบ เสนอผู้บังคับบัญชาเพื่อลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 82,
      "job_template_id": 1,
      "job_group_id": 6,
      "job_subitem_id": 15,
      "job_process_id": 82,
      "job_group_name": "งานงบประมาณ (ตามระเบียบฯว่าด้วยงบประมาณ)",
      "job_item_name": "งานงบประมาณ (ตามระเบียบฯว่าด้วยงบประมาณ)",
      "job_process_name": " เมื่อผู้บังคับบัญชาลงนามแล้ว ออกเลขหนังสือ และนำส่งหนังสือถึงสำนักบริหารงบปะมาณต่อไป",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 83,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 16,
      "job_process_id": 83,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "ค่าป่วยการพยานและค่ายานพาหนะพยาน",
      "job_process_name": "รับหลักฐานการเบิกความพยานและหมายเรียกศาล ตรวจสอบความถูกต้องตามระเบียบการเบิกจ่ายค่าป่วยการและค่าพาหนะพยาน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 84,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 16,
      "job_process_id": 84,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "ค่าป่วยการพยานและค่ายานพาหนะพยาน",
      "job_process_name": "พิมพ์ใบเบิกเงินและใบสำคัญรับเงินแทนใบเสร็จรับเงิน ให้พยานลงลายมือชื่อรับเงิน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 85,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 16,
      "job_process_id": 85,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "ค่าป่วยการพยานและค่ายานพาหนะพยาน",
      "job_process_name": "ลงบัญชีควบคุมการใช้จ่ายเงินค่าป่วยการพยานและค่าพาหนะพยาน ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 86,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 16,
      "job_process_id": 86,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "ค่าป่วยการพยานและค่ายานพาหนะพยาน",
      "job_process_name": "รายงานการใช้จ่ายเงินเสนออัยการพิเศษฝ่าย ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 87,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 17,
      "job_process_id": 87,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเงินยืมและงานล้างบัญชีเงินยืม",
      "job_process_name": " รับและรวบรวมใบขอยืมเงินหรือใบล้างเงินยืมจากข้าราชการในสังกัด",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 88,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 17,
      "job_process_id": 88,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเงินยืมและงานล้างบัญชีเงินยืม",
      "job_process_name": "ตรวจสอบหลักฐานการเบิกจ่ายเงินที่ได้รับ ว่าครบถ้วนถูกต้องหรือไม่ ค้นระเบียบการเบิกจ่ายที่เกี่ยวข้อง ว่าสามารถดำเนินการเบิกจ่ายได้หรือไม่",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 89,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 17,
      "job_process_id": 89,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเงินยืมและงานล้างบัญชีเงินยืม",
      "job_process_name": "จัดทำใบขอเบิกหรือใบล้างบัญชีเงินยืม เสนออัยการพิเศษฝ่ายพิจารณาลงนาม ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 90,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 17,
      "job_process_id": 90,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเงินยืมและงานล้างบัญชีเงินยืม",
      "job_process_name": "พิมหนังสือนำส่งรายงานการใบขอยืมเงินหรือใบล้างบัญชีเงินยืม เสนออัยการพิเศษฝ่ายพิจารณาลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 91,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 17,
      "job_process_id": 91,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเงินยืมและงานล้างบัญชีเงินยืม",
      "job_process_name": "ออกเลขหนังสือนำส่งแบบสำนักงานการคลัง",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 92,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 18,
      "job_process_id": 92,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเบิกค่าใช้จ่ายต่าง ๆ (ค่าเช่าบ้าน, ค่าเล่าเรียน, ค่ารักษา, ค่าน้ำ, ค่าไฟฟ้า, ค่าเดินทาง, ค่าปฏิบัติงานนอกเวลา เป็นต้น)",
      "job_process_name": "ตรวจสอบความถูกต้องครบถ้วนของเอกสารที่ใช้ประกอบการเบิกจ่าย  ตรวจสอบระเบียบการเบิกค่าใช้จ่ายต่าง ๆ ที่เกี่ยวข้องว่าถูกต้องเป็นตามไปตามระเบียบหรือไม่",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 93,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 18,
      "job_process_id": 93,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเบิกค่าใช้จ่ายต่าง ๆ (ค่าเช่าบ้าน, ค่าเล่าเรียน, ค่ารักษา, ค่าน้ำ, ค่าไฟฟ้า, ค่าเดินทาง, ค่าปฏิบัติงานนอกเวลา เป็นต้น)",
      "job_process_name": "จัดทำแบบขอเบิกค่าใช้จ่ายแบบการเบิกที่กระทรวงการคลังหรือกรมบัญชีกลางกำหนด",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 94,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 18,
      "job_process_id": 94,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเบิกค่าใช้จ่ายต่าง ๆ (ค่าเช่าบ้าน, ค่าเล่าเรียน, ค่ารักษา, ค่าน้ำ, ค่าไฟฟ้า, ค่าเดินทาง, ค่าปฏิบัติงานนอกเวลา เป็นต้น)",
      "job_process_name": "เสนอผู้บังคับบัญชาตามลำดับชั้นเพื่อพิจารณาลงนาม ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 95,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 18,
      "job_process_id": 95,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเบิกค่าใช้จ่ายต่าง ๆ (ค่าเช่าบ้าน, ค่าเล่าเรียน, ค่ารักษา, ค่าน้ำ, ค่าไฟฟ้า, ค่าเดินทาง, ค่าปฏิบัติงานนอกเวลา เป็นต้น)",
      "job_process_name": "ออกเลขหนังสือนำส่งแบบขอเบิก",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 96,
      "job_template_id": 1,
      "job_group_id": 7,
      "job_subitem_id": 18,
      "job_process_id": 96,
      "job_group_name": "งานการเงินและบัญชี",
      "job_item_name": "งานเบิกค่าใช้จ่ายต่าง ๆ (ค่าเช่าบ้าน, ค่าเล่าเรียน, ค่ารักษา, ค่าน้ำ, ค่าไฟฟ้า, ค่าเดินทาง, ค่าปฏิบัติงานนอกเวลา เป็นต้น)",
      "job_process_name": "นำส่งสำนักงานการคลัง เพื่อเบิกจ่ายตามระเบียบ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 97,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 19,
      "job_process_id": 97,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานพัสดุประจำปี(พรบ.พัสดุฯ)",
      "job_process_name": "สำรวจพัสดุเพื่อตรวจสอบว่ามีพัสดุคงเหลือ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 98,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 19,
      "job_process_id": 98,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานพัสดุประจำปี(พรบ.พัสดุฯ)",
      "job_process_name": "ตรวจสอบพัสดุคงเหลือของสำนักงาน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 99,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 19,
      "job_process_id": 99,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานพัสดุประจำปี(พรบ.พัสดุฯ)",
      "job_process_name": " จัดทำและพิมพ์รายละเอียดพัสดุคงเหลือ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 100,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 19,
      "job_process_id": 100,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานพัสดุประจำปี(พรบ.พัสดุฯ)",
      "job_process_name": "พิมพ์หนังสือนำส่งรายงานพัสดุ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 101,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 19,
      "job_process_id": 101,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานพัสดุประจำปี(พรบ.พัสดุฯ)",
      "job_process_name": "เสนอผู้บังคับบัญชาเพื่อพิจารณาลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 102,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 19,
      "job_process_id": 102,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานพัสดุประจำปี(พรบ.พัสดุฯ)",
      "job_process_name": "นำส่งสำนักบริหารทรัพย์สิน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 103,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 20,
      "job_process_id": 103,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานครุภัณฑ์ประจำปี",
      "job_process_name": "สำรวจครุภัณฑ์ของสำนักงานว่ามีครุภัณฑ์ใดชำรุดหรือเสียหายหรือไม่ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 104,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 20,
      "job_process_id": 104,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานครุภัณฑ์ประจำปี",
      "job_process_name": "ตรวจสอบครุภัณฑ์ของสำนักงานและรับรายงานจากสำนักงานอัยการพิเศษฝ่าย",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 105,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 20,
      "job_process_id": 105,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานครุภัณฑ์ประจำปี",
      "job_process_name": "จัดทำและพิมพ์รายละเอียดครุภัณฑ์",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 106,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 20,
      "job_process_id": 106,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานครุภัณฑ์ประจำปี",
      "job_process_name": "พิมพ์หนังสือนำส่งรายงานครุภัณฑ์",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 107,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 20,
      "job_process_id": 107,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานครุภัณฑ์ประจำปี",
      "job_process_name": "เสนอผู้บังคับบัญชาเพื่อพิจารณาลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 108,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 20,
      "job_process_id": 108,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรายงานครุภัณฑ์ประจำปี",
      "job_process_name": "นำส่งสำนักบริหารทรัพย์สิน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 109,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 21,
      "job_process_id": 109,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานเบิกพัสดุ ครุภัณฑ์",
      "job_process_name": "จัดทำบันทึกข้อความเพื่อขอเบิกพัสดุ ครุภัณฑ์ ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 110,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 21,
      "job_process_id": 110,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานเบิกพัสดุ ครุภัณฑ์",
      "job_process_name": "เสนออธิบดีอัยการเพื่อพิจารณาลงนาม ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 111,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 21,
      "job_process_id": 111,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานเบิกพัสดุ ครุภัณฑ์",
      "job_process_name": "ออกเลขหนังสือนำส่ง",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 112,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 21,
      "job_process_id": 112,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานเบิกพัสดุ ครุภัณฑ์",
      "job_process_name": "นำส่งสำนักบริหารทรัพย์สิน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 113,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 22,
      "job_process_id": 113,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรับบริจาคครุภัณฑ์",
      "job_process_name": "จัดทำบันทึกการได้รับบริจาคครุภัณฑ์จากบุคคลใดๆ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 114,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 22,
      "job_process_id": 114,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรับบริจาคครุภัณฑ์",
      "job_process_name": "เสนออธิบดีอัยการพิจารณาลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 115,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 22,
      "job_process_id": 115,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานรับบริจาคครุภัณฑ์",
      "job_process_name": "นำส่งสำนักบริหารทรัพย์สิน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 116,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 23,
      "job_process_id": 116,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานแจ้งซ่อม",
      "job_process_name": "จัดทำบันทึกข้อความแจ้งซ่อมหากเกิดกรณีมีครุภัณฑ์เสียหาย",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 117,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 23,
      "job_process_id": 117,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานแจ้งซ่อม",
      "job_process_name": "เสนออธิบดีอัยการพิจารณาลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 118,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 23,
      "job_process_id": 118,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานแจ้งซ่อม",
      "job_process_name": "ออกเลขหนังสือนำส่ง",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 119,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 23,
      "job_process_id": 119,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานแจ้งซ่อม",
      "job_process_name": "ส่งสำนักบริหารทรัพย์สินเพื่อดำเนินการต่อไป",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 120,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 24,
      "job_process_id": 120,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานทะเบียนคุมทรัพย์สิน",
      "job_process_name": "จัดทำทะเบียนคุมทรัพย์สินวัสดุ และครุภัณฑ์ของสำนักงาน เพื่อการตรวจสอบ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 121,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 25,
      "job_process_id": 121,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานอาคารสถานที่ (ตามคำสั่งสำนักงานอัยการสูงสุด)",
      "job_process_name": "ในฐานะผู้ดูแลรับผิดชอบอาคารสถานที่ตามที่อัยการสูงสุดมอบหมาย ประสานงานกับฝ่ายบริหารทั่วไป สำนักบริหารกลางประจำอาคาร ซึ่งเป็นหน่วยงานรับผิดชอบหลักที่อัยการสูงสุดมอบหมาย และมีหน้าที่บริหารจัดการ พัฒนา ดูแลรับผิดชอบอาคาร กำหนดแนวทางบริหารจัดการพื้นที่แก้ไขปัญหาเสนอแนะการแก้ไขปัญหาเกี่ยวกับอาคาร สถานที่จอดรถภายในอาคาร ตามที่อธิบดีอัยการมอบหมาย",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 122,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 25,
      "job_process_id": 122,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานอาคารสถานที่ (ตามคำสั่งสำนักงานอัยการสูงสุด)",
      "job_process_name": "รับรายงานการตรวจสถานที่ของพนักงานรักษาความปลอดภัย เสนออธิบดีอัยการ เพื่อทราบ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 123,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 25,
      "job_process_id": 123,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานอาคารสถานที่ (ตามคำสั่งสำนักงานอัยการสูงสุด)",
      "job_process_name": "รับรายงานการดูแลรักษาความสะอาดของพนักงานรักษาความสะอาด  เสนออธิบดีอัยการ เพื่อทราบ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 124,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 25,
      "job_process_id": 124,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานอาคารสถานที่ (ตามคำสั่งสำนักงานอัยการสูงสุด)",
      "job_process_name": "รับแจ้งอาคารชำรุดจากข้าราชการและเจ้าหน้าที่ในสำนักงาน ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 125,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 25,
      "job_process_id": 125,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานอาคารสถานที่ (ตามคำสั่งสำนักงานอัยการสูงสุด)",
      "job_process_name": "จัดทำบันทึกข้อความแจ้งซ่อมกรณีอาคาร ชำรุดเสียหาย เสนออธิบดีอัยการพิจารณาลงนาม ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 126,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 25,
      "job_process_id": 126,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานอาคารสถานที่ (ตามคำสั่งสำนักงานอัยการสูงสุด)",
      "job_process_name": "เมื่อลงนามแล้ว ส่งออกเลขหนังสือ และนำส่งฝ่ายบริหารทั่วไป สำนักบริหารกลางประจำอาคารดำเนินการต่อไป",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 127,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 26,
      "job_process_id": 127,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานยานพาหนะ (ตามระเบียบฯว่าด้วยรถราชการและเงินตอบแทนฯ)",
      "job_process_name": "จัดทำทะเบียนคุมการใช้ยานพาหนะของสำนักงาน (กรณีมียานพาหนะเป็นของตนเอง) และเก็บรักษา fleetcard ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 128,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 26,
      "job_process_id": 128,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานยานพาหนะ (ตามระเบียบฯว่าด้วยรถราชการและเงินตอบแทนฯ)",
      "job_process_name": "รับใบคำขออนุญาตใช้รถยนต์ส่วนกลางตามความจำเป็นต้องใช้ เสนออธิบอัยการหรือผู้ที่ได้รับมอบหมาย อนุญาตให้ใช้รถยนต์ส่วนกลาง ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 129,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 26,
      "job_process_id": 129,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานยานพาหนะ (ตามระเบียบฯว่าด้วยรถราชการและเงินตอบแทนฯ)",
      "job_process_name": "จัดทำรายงานการใช้น้ำมันเชื้อเพลิง เสนออธิบดีอัยการเพื่อลงนาม ",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 130,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 26,
      "job_process_id": 130,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานยานพาหนะ (ตามระเบียบฯว่าด้วยรถราชการและเงินตอบแทนฯ)",
      "job_process_name": "ออกเลขหนังสือ และส่งสำนักการคลัง",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 131,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 26,
      "job_process_id": 131,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานยานพาหนะ (ตามระเบียบฯว่าด้วยรถราชการและเงินตอบแทนฯ)",
      "job_process_name": "รับแจ้งซ่อมรถยนต์ส่วนกลางพร้อมจัดทำบันทึกข้อความขอซ่อมแซมรถยนต์ เสนอผู้บังคับบัญชาลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 132,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 26,
      "job_process_id": 132,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานยานพาหนะ (ตามระเบียบฯว่าด้วยรถราชการและเงินตอบแทนฯ)",
      "job_process_name": "ออกเลขหนังสือ และส่งสำนักบริหารทรัพย์สิน",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 133,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 26,
      "job_process_id": 133,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานยานพาหนะ (ตามระเบียบฯว่าด้วยรถราชการและเงินตอบแทนฯ)",
      "job_process_name": "กรณีไม่มียานพาหนะของสำนักงาน  จัดทำใบคำขออนุญาตใช้รถยนต์ส่วนกลางตามความจำเป็นต้องใช้ เสนออธิบดีอัยการเพื่อพิจารณาลงนาม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 134,
      "job_template_id": 1,
      "job_group_id": 8,
      "job_subitem_id": 26,
      "job_process_id": 134,
      "job_group_name": "งานพัสดุ ยานพาหนะ และอาคารสถานที่",
      "job_item_name": "งานยานพาหนะ (ตามระเบียบฯว่าด้วยรถราชการและเงินตอบแทนฯ)",
      "job_process_name": "ยื่นใบคำขออนุญาตใช้รถยนต์ส่วนกลางที่ฝ่ายบริหารงานทั่วไป สำนักบริหารกลาง ประจำอาคาร",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 135,
      "job_template_id": 1,
      "job_group_id": 9,
      "job_subitem_id": 27,
      "job_process_id": 135,
      "job_group_name": "งานประชุม",
      "job_item_name": "งานประชุม",
      "job_process_name": "- ดำเนินการเตรียมความพร้อมจองห้องประชุม เอกสาร ประสานงาน และติดต่อประสานงานอันเกี่ยวข้องกับงานประชุม",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 136,
      "job_template_id": 1,
      "job_group_id": 10,
      "job_subitem_id": 28,
      "job_process_id": 136,
      "job_group_name": "งานตามแผนยุทธศาสตร์  แผนงาน โครงการ",
      "job_item_name": "งานตามแผนยุทธศาสตร์  แผนงาน โครงการ",
      "job_process_name": "ดำเนินการให้หน่วยงานในสังกัดปฏิบัติตามตามแผนยุทธศาสตร์ แผนงาน โครงการ ตามนโยบายอัยการสูงสุด",
      "base_unit_id": null,
      "base_unit_name": null
    },
    {
      "job_template_items_id": 137,
      "job_template_id": 1,
      "job_group_id": 10,
      "job_subitem_id": 28,
      "job_process_id": 137,
      "job_group_name": "งานตามแผนยุทธศาสตร์  แผนงาน โครงการ",
      "job_item_name": "งานตามแผนยุทธศาสตร์  แผนงาน โครงการ",
      "job_process_name": "ดำเนินการตามแผนยุทธศาสตร์ แผนงาน โครงการ ตามนโยบายอัยการสูงสุด",
      "base_unit_id": null,
      "base_unit_name": null
    }
  ]

  groupItems: any = [];

  constructor () {

  }

  ngOnInit() {
    var _items = _.groupBy(this.items, "job_group_name");

    console.log(_items);
    var groups = [];

    for (const [key, value] of Object.entries(_items)) {
      console.log(key);
      groups.push(key);
    }

    var choices: any = [];

    groups.forEach((v: any) => {
      var obj: any = {};
      obj.group_name = v;
      obj.items = [];

      this.items.forEach((x: any) => {
        if (x.job_group_name === v) {
          obj.items.push(x);
        }
      });

      choices.push(obj);
    });

    console.log(choices);
    this.groupItems = choices;
  }
}
